//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoHDR.ProjectResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Locale_Texts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Locale_Texts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AutoHDR.ProjectResources.Locale_Texts", typeof(Locale_Texts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate HDR.
        /// </summary>
        public static string ActivateHDR {
            get {
                return ResourceManager.GetString("ActivateHDR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add application.
        /// </summary>
        public static string AddApplication {
            get {
                return ResourceManager.GetString("AddApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AutoHDR is already running..
        /// </summary>
        public static string AlreadyRunning {
            get {
                return ResourceManager.GetString("AlreadyRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application name.
        /// </summary>
        public static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applications.
        /// </summary>
        public static string Applications {
            get {
                return ResourceManager.GetString("Applications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AutoHDR.
        /// </summary>
        public static string AutoHDR {
            get {
                return ResourceManager.GetString("AutoHDR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable HDR on this monitor, based on the applications.
        /// </summary>
        public static string AutoHDRToolTip {
            get {
                return ResourceManager.GetString("AutoHDRToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-Start.
        /// </summary>
        public static string AutoStart {
            get {
                return ResourceManager.GetString("AutoStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy me a beer!.
        /// </summary>
        public static string BuyBeer {
            get {
                return ResourceManager.GetString("BuyBeer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changelog.
        /// </summary>
        public static string Changelog {
            get {
                return ResourceManager.GetString("Changelog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for new version on startup.
        /// </summary>
        public static string CheckForNewVersion {
            get {
                return ResourceManager.GetString("CheckForNewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose application.
        /// </summary>
        public static string ChooseApplication {
            get {
                return ResourceManager.GetString("ChooseApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose UWP app....
        /// </summary>
        public static string ChooseUWPApplication {
            get {
                return ResourceManager.GetString("ChooseUWPApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restarts the application on first occurence, as the application may need HDR to be activated before launching it..
        /// </summary>
        public static string CompatibilityModeToolTip {
            get {
                return ResourceManager.GetString("CompatibilityModeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current application.
        /// </summary>
        public static string CurrentApplication {
            get {
                return ResourceManager.GetString("CurrentApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deactivate HDR.
        /// </summary>
        public static string DeactivateHDR {
            get {
                return ResourceManager.GetString("DeactivateHDR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device ID.
        /// </summary>
        public static string DeviceID {
            get {
                return ResourceManager.GetString("DeviceID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display name.
        /// </summary>
        public static string DisplayName {
            get {
                return ResourceManager.GetString("DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download from GitHub.
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string DownloadNewestVersion {
            get {
                return ResourceManager.GetString("DownloadNewestVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to restart application..
        /// </summary>
        public static string ExceptionRestartProcess {
            get {
                return ResourceManager.GetString("ExceptionRestartProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File path.
        /// </summary>
        public static string FilePath {
            get {
                return ResourceManager.GetString("FilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GitHub.
        /// </summary>
        public static string GitHub {
            get {
                return ResourceManager.GetString("GitHub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use automated HDR Mode for all monitors.
        /// </summary>
        public static string GlobalAutoHDR {
            get {
                return ResourceManager.GetString("GlobalAutoHDR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desktop is using HDR.
        /// </summary>
        public static string GlobalDesktopDefaultHDROnOff {
            get {
                return ResourceManager.GetString("GlobalDesktopDefaultHDROnOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HDR.
        /// </summary>
        public static string HDR {
            get {
                return ResourceManager.GetString("HDR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto HDR Mode.
        /// </summary>
        public static string HDRMode {
            get {
                return ResourceManager.GetString("HDRMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon.
        /// </summary>
        public static string Icon {
            get {
                return ResourceManager.GetString("Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local.
        /// </summary>
        public static string Local {
            get {
                return ResourceManager.GetString("Local", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging.
        /// </summary>
        public static string Logging {
            get {
                return ResourceManager.GetString("Logging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon Logo {
            get {
                object obj = ResourceManager.GetObject("Logo", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automated HDR mode.
        /// </summary>
        public static string ManagedHDR {
            get {
                return ResourceManager.GetString("ManagedHDR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close to tray.
        /// </summary>
        public static string MinimizeToTray {
            get {
                return ResourceManager.GetString("MinimizeToTray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitors.
        /// </summary>
        public static string Monitors {
            get {
                return ResourceManager.GetString("Monitors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No application is running.
        /// </summary>
        public static string NoApplication {
            get {
                return ResourceManager.GetString("NoApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online.
        /// </summary>
        public static string Online {
            get {
                return ResourceManager.GetString("Online", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prevent HDR.
        /// </summary>
        public static string PreventHDROnProgramStart {
            get {
                return ResourceManager.GetString("PreventHDROnProgramStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh rate [Hz].
        /// </summary>
        public static string RefreshRate {
            get {
                return ResourceManager.GetString("RefreshRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release date.
        /// </summary>
        public static string ReleaseDate {
            get {
                return ResourceManager.GetString("ReleaseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove application.
        /// </summary>
        public static string RemoveApplication {
            get {
                return ResourceManager.GetString("RemoveApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolution.
        /// </summary>
        public static string Resolution {
            get {
                return ResourceManager.GetString("Resolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compatibility mode.
        /// </summary>
        public static string RestartProccessOnFirstOccurence {
            get {
                return ResourceManager.GetString("RestartProccessOnFirstOccurence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit application.
        /// </summary>
        public static string Shutdown {
            get {
                return ResourceManager.GetString("Shutdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start in HDR-Mode.
        /// </summary>
        public static string StartInHDR {
            get {
                return ResourceManager.GetString("StartInHDR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start to tray.
        /// </summary>
        public static string StartToTray {
            get {
                return ResourceManager.GetString("StartToTray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume sync devices.
        /// </summary>
        public static string VolumeSyncDevices {
            get {
                return ResourceManager.GetString("VolumeSyncDevices", resourceCulture);
            }
        }
    }
}
